applicationController:
  containerPort: 8082
  servicePort: 8082
  image:
    repository: argoproj/argocd
    tag: v1.1.2
    pullPolicy: Always
  volumeMounts: []
  volumes:
    - name: known-hosts
      configMap:
        name: argocd-known-hosts

server:
  containerPort: 8080
  servicePortHttp: 80
  servicePortHttps: 443
  serviceAnnotations: {}
  image:
    repository: argoproj/argocd
    tag: v1.1.2
    pullPolicy: Always
  uiInitImage:
    repository: argoproj/argocd-ui
    tag: v1.1.2
    pullPolicy: Always
  extraArgs: []
  volumeMounts: []
  volumes: []
  annotations: {}

repoServer:
  containerPort: 8081
  servicePort: 8081
  image:
    repository: argoproj/argocd
    tag: v1.1.2
    pullPolicy: Always
  volumeMounts: []
  volumes: []

dexServer:
  containerPortHttp: 5556
  containerPortGrpc: 5557
  servicePortHttp: 5556
  servicePortGrpc: 5557
  image:
    repository: quay.io/dexidp/dex
    tag: v2.14.0
    pullPolicy: Always
  initImage:
    repository: argoproj/argocd
    tag: v1.1.2
    pullPolicy: Always
  volumeMounts: []
  volumes: []

# terminate tls at ArgoCD level
ingress:
  enabled: false
  annotations:
    {}
    # kubernetes.io/ingress.class: nginx
    # nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    # nginx.ingress.kubernetes.io/ssl-passthrough: "true"
  path: /
  hosts:
    - argocd.example.com

# Standard Argo CD installation with cluster-admin access.
# Set this true if you plan to use Argo CD to deploy applications in the same cluster that
#     Argo CD runs in (i.e. kubernetes.svc.default).
# Will still be able to deploy to external clusters with inputted credentials.

clusterAdminAccess:
  enabled: true

config:
  # bcrypt hash of the admin password (autogenerated on initial startup).
  # To reset a forgotten password, delete this key and restart the argocd-server
  admin:
    password: JDJiJDEyJFZnS3Rvdzc1VXlCTElEdlRTTjF3eXVVZEYzc1IvcFJiTFMuaWpubEZUWnRXSncuWW4yLkp5
    passwordMtime: MjAxOS0wNS0wMiAwMjowOToyOC0wNzowMA==

  server:
    # random server signature key for session validation (autogenerated on initial startup)
    # server.secretkey:
    secretkey:

  # TLS certificate and private key for API server
  tls:
    crt: >-
      # multi-line crt string can go here
    key: >-
      # multi-line key string can go here

  knownHosts: >-
    # multi-line known-hosts entry for git ssh access

  helmRepositories:
    #- name: jetstack
    #  url: https://charts.jetstack.io
    #- name: argo
    #  url: https://argoproj.github.io/argo-helm
    #- name: gitlab
    #  url: https://charts.gitlab.io
  repositories:
    #- url: git@github.com:example/repo.git
    #  sshPrivateKeySecret:
    #    key: sshPrivateKey
    #    name: repo-key-secret
    #  insecureIgnoreHostKey: yes
    # - url: git@gitlab.com:usersprivategroup/users-gitops-config.git
    #   sshPrivateKeySecret:
    #     key: privateKey
    #     name: argocd-dev-key
    # - url: git@gitlab.com:accountingprivategroup/accounting-gitops-config.git
    #   sshPrivateKeySecret:
    #     key: privateKey
    #     name: argocd-dev-key
  dexConfig:
    #   # Argo CD's externally facing base URL. Required for configuring SSO
    #   # url: https://argo-cd-demo.argoproj.io
    #
    #   # A dex connector configuration. See documentation on how to configure SSO:
    #   # https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/sso.md#2-configure-argo-cd-for-sso
    connectors:
      - type: oidc
        id: google
        name: Google
        config:
          issuer: https://accounts.google.com
          clientID:
          clientSecret:
          redirectURI:
    #   # GitHub example
    #   - type: github
    #     id: github
    #     name: GitHub
    #     config:
    #       clientID: aabbccddeeff00112233
    #       clientSecret: $dex.github.clientSecret
    #       orgs:
    #       - name: your-github-org
    #         teams:
  url: # https://argocd.example.com/
  oidcConfig:
    # name: Okta
    # issuer: https://dev-123456.oktapreview.com
    # clientID: aaaabbbbccccddddeee
    # clientSecret: $oidc.okta.clientSecret
  # The following keys hold the shared secret for authenticating GitHub/GitLab/BitBucket webhook
  # events. To enable webhooks, configure one or more of the following keys with the shared git
  # provider webhook secret. The payload URL configured in the git provider should use the
  # /api/webhook endpoint of your Argo CD instance (e.g. https://argocd.example.com/api/webhook)
  webhook:
    githubSecret:
    gitlabSecret:
    bitbucketSecret:
  # resourceCustomizations can be used to create custom health checks for resources
  # https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/health.md#way-1-define-a-custom-health-check-in-argocd-cm-configmap
  resourceCustomizations:
    admissionregistration.k8s.io/MutatingWebhookConfiguration:
      # List of json pointers in the object to ignore differences
      ignoreDifferences: |
        jsonPointers:
        - /webhooks/0/clientConfig/caBundle
  #   certmanager.k8s.io/Certificate:
  #     health.lua: |
  #       hs = {}
  #       ...
  #       return hs
  configManagementPlugins:
    # - name: pluginName
    #   init:                          # Optional command to initialize application source directory
    #     command: ["sample command"]
    #     args: ["sample args"]
    #   generate:                      # Command to generate manifests YAML
    #     command: ["sample command"]
    #     args: ["sample args"]

rbac:
  #   # An RBAC policy .csv file containing additional policy and role definitions.
  #   # See https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/rbac.md on how to write RBAC policies.
  #   policy.csv: |
  #     # Give all members of "my-org:team-alpha" the ability to sync apps in "my-project"
  #     p, my-org:team-alpha, applications, sync, my-project/*, allow
  #     # Make all members of "my-org:team-beta" admins
  #     g, my-org:team-beta, role:admin
  policyCsv: #|
  #   p, role:org-admin, applications, *, */*, allow
  #   p, role:org-admin, clusters, get, *, allow
  #   p, role:org-admin, repositories, get, *, allow
  #   p, role:org-admin, repositories, create, *, allow
  #   p, role:org-admin, repositories, update, *, allow
  #   p, role:org-admin, repositories, delete, *, allow
  #   g, your-github-org:your-team, role:org-admin
  # The default role Argo CD will fall back to, when authorizing API requests
  policyDefault: role:admin
  # Scopes controls which OIDC scopes to examine during rbac enforcement (in addition to `sub` scope).
  scopes: #[groups]

redis:
  image:
    repository: redis
    tag: 5.0.3
    pullPolicy: Always
  containerPort: 6379
  servicePort: 6379
