apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: argocds.cna.mirantis.com
spec:
  group: cna.mirantis.com
  names:
    kind: Argocd
    listKind: ArgocdList
    plural: argocds
    singular: argocd
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
